version: '3'

tasks:
  default:
    desc: "Build for both OS"
    cmds:
      - task: build-windows
      - task: build-linux

  build-windows:
    desc: "Compile for Windows"
    env:
      GOOS: windows
      GOARCH: amd64
    cmds:
      - go build -o bin/encounter-manager.exe

  build-linux:
    desc: "Compile for Linux"
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build -o bin/encounter-manager-linux